### PR TITLE
[parquet-sdk-migration] replace Rc with Arc to support thread-safety

### PR DESCRIPTION
**Pull request by yuunlimm**
### Description
The run_processor function in ParquetDefaultProcessor fails because ProcessorBuilder (or fanout_builder) uses Rc<RefCell<>>, which is not Send.  And, inside of fanout_broadcast we send the graph into multiple threads here: [https://github.com/aptos-labs/aptos-indexer-processors-sdk/blob/343a2d01dce9f8bca7[…]tos-indexer-processors-sdk/sdk/src/builder/processor_builder.rs](https://github.com/aptos-labs/aptos-indexer-processors-sdk/blob/343a2d01dce9f8bca76b90d506f61c1a07943e4b/aptos-indexer-processors-sdk/sdk/src/builder/processor_builder.rs#L358)

### Test Plan
parquet processor runs fine
Screenshot 2024-11-05 at 10 38 47 AM

### CODE REVIEW

**Comment by yuunlimm** [comment]
* **#79** <a href="https://app.graphite.dev/github/pr/aptos-labs/aptos-indexer-processor-sdk/79?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @yuunlimm and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by rtso** [comment]
Can you also screenshot/add to test plan the graphviz? You can use the ProcessorBuilder from the tests in lib.rs.

**Comment by yuunlimm** [comment]
Screenshot 2024-11-05 at 4 50 44 PM

**Review by rtso — APPROVED** [review]
nice! i'll stamp to unblock

**Pull request merged**
